#!/usr/bin/expect
set timeout 20
if { $argc < 3 } {
  puts "Usage: $argv0 %SRC_FULL_PATH% %SRC_IP% %DST_IP%"
  exit 1
}
set path [lindex $argv 0]
set file [file tail $path]
set ip [lindex $argv 1]
set localhost [lindex $argv 2]
set user root
set password password

spawn telnet $ip
expect "'^]'."
sleep .1;
expect "login:"
send "$user\r"
expect "Password:"
send "$password\r"
expect "#"
send "ftpput -P2121 $localhost $file $path\r"
expect "#"
